<?php

namespace Yonke\CityHondaBundle\Repository;

/**
 * AutosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutosRepository extends \Doctrine\ORM\EntityRepository
{
}
